### ISSUE TITLE
.eslintcache

### ISSUE THREAD

**Issue by Goolgae** [KimGiHong/React-study#2]
@KimGiHong 
> [`.eslintcache`](https://www.reddit.com/r/reactjs/comments/kh79ks/eslintcache_file/) 파일이 원격저장소에 올라와있어요.

캐쉬삭제하고 [.gitignore](https://velog.io/@dev-hannahk/.eslintcache-gitignore)에 추가토록 합시다!.

**Comment by KimGiHong** [comment]
공부해놓고 까먹고 있었네요 감사합니다
